// src/components/filter-toolbar/filter-toolbar.tsx
'use client'

import { useState } from 'react'
import { Plus } from 'lucide-react'

import type { Table } from '@tanstack/react-table'

import { Button } from '#/components/ui/button'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '#/components/ui/popover'
import { FilterConditionEditor } from './filter-condition-editor'
import { formatConditionValue, operatorRegistry } from './operators'
import type { FilterCondition } from './operators'
import { useFilterConditions } from './use-filter-conditions'
import './types'

export interface FilterToolbarProps<TData> {
  table: Table<TData>
}

export function FilterToolbar<TData>({ table }: FilterToolbarProps<TData>) {
  const conditions = useFilterConditions(table)
  const filterableColumns = table
    .getAllColumns()
    .filter((column) => column.columnDef.meta?.filterVariant)

  if (filterableColumns.length === 0) return null

  const activeColumnIds = new Set(conditions.map((c) => c.columnId))
  const availableColumnIds = filterableColumns
    .filter((column) => !activeColumnIds.has(column.id))
    .map((column) => column.id)

  return (
    <div className="flex flex-wrap items-center gap-2">
      {conditions.map((condition) => (
        <FilterConditionPill
          key={condition.columnId}
          table={table}
          condition={condition}
        />
      ))}

      {availableColumnIds.length > 0 && (
        <AddFilterTrigger table={table} availableColumnIds={availableColumnIds} />
      )}
    </div>
  )
}

function AddFilterTrigger<TData>({
  table,
  availableColumnIds,
}: {
  table: Table<TData>
  availableColumnIds: string[]
}) {
  const [open, setOpen] = useState(false)

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button type="button" variant="outline" size="sm">
          <Plus className="h-4 w-4" />
          Add filter
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-64 p-0" align="start">
        <FilterConditionEditor
          table={table}
          availableColumnIds={availableColumnIds}
          onApply={(columnId, operator, value) => {
            table.getColumn(columnId)?.setFilterValue({ operator, value })
            setOpen(false)
          }}
        />
      </PopoverContent>
    </Popover>
  )
}

function FilterConditionPill<TData>({
  table,
  condition,
}: {
  table: Table<TData>
  condition: FilterCondition
}) {
  const [open, setOpen] = useState(false)
  const meta = table.getColumn(condition.columnId)?.columnDef.meta
  const operators = meta?.filterVariant ? operatorRegistry[meta.filterVariant] : []
  const activeOperator = operators.find((o) => o.value === condition.operator)

  if (!meta?.filterVariant) return null

  const valueDisplay = formatConditionValue(
    meta.filterVariant,
    activeOperator,
    condition.value,
    meta.filterOptions,
  )

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button type="button" variant="outline" size="sm">
          <span>{meta.label}</span>
          <span className="text-muted-foreground">{activeOperator?.label}</span>
          {valueDisplay && <span className="font-medium">{valueDisplay}</span>}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-64 p-0" align="start">
        <FilterConditionEditor
          table={table}
          columnId={condition.columnId}
          initialOperator={condition.operator}
          initialValue={condition.value}
          onApply={(columnId, operator, value) => {
            table.getColumn(columnId)?.setFilterValue({ operator, value })
            setOpen(false)
          }}
          onRemove={() => {
            table.getColumn(condition.columnId)?.setFilterValue(undefined)
            setOpen(false)
          }}
        />
      </PopoverContent>
    </Popover>
  )
}

// src/components/vue/filter-toolbar/FilterToolbar.vue
<script setup lang="ts" generic="TData">
import { computed } from 'vue'
import type { Table } from '@tanstack/vue-table'
import AddFilterTrigger from './AddFilterTrigger.vue'
import FilterConditionPill from './FilterConditionPill.vue'
import { useFilterConditions } from './use-filter-conditions'
import './types'

const props = defineProps<{ table: Table<TData> }>()

const conditions = useFilterConditions(props.table)

const filterableColumns = computed(() =>
  props.table
    .getAllColumns()
    .filter((column) => column.columnDef.meta?.filterVariant),
)

const availableColumnIds = computed(() => {
  const activeColumnIds = new Set(conditions.value.map((c) => c.columnId))
  return filterableColumns.value
    .filter((column) => !activeColumnIds.has(column.id))
    .map((column) => column.id)
})
</script>

<template>
  <div
    v-if="filterableColumns.length > 0"
    class="flex flex-wrap items-center gap-2"
  >
    <FilterConditionPill
      v-for="condition in conditions"
      :key="condition.columnId"
      :table="table"
      :condition="condition"
    />

    <AddFilterTrigger
      v-if="availableColumnIds.length > 0"
      :table="table"
      :available-column-ids="availableColumnIds"
    />
  </div>
</template>
