// src/components/v9/basic/data-table-filter.tsx
import type { Column, RowData } from '@tanstack/react-table-v9'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '#/components/ui/select'
import type { V9Features } from '#/lib/table-v9-features.ts'

type Props<TData extends RowData> = {
  column?: Column<V9Features, TData, unknown>
  title: string
  options: { value: string; label: string }[]
}

export function DataTableFilter<TData extends RowData>({
  column,
  title,
  options,
}: Props<TData>) {
  const filterValue = column?.getFilterValue() as string | undefined

  return (
    <Select
      onValueChange={(val) => {
        column?.setFilterValue(val)
      }}
      value={filterValue}
    >
      <SelectTrigger className="w-45">
        <SelectValue placeholder={title} />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          {options.map((option) => (
            <SelectItem key={option.value} value={option.value}>
              {option.label}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  )
}

// src/components/vue/basic/DataTableFilter.vue
<script setup lang="ts" generic="TData">
import type { Column } from '@tanstack/vue-table'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

const props = defineProps<{
  column?: Column<TData, unknown>
  title: string
  options: { value: string; label: string }[]
}>()
</script>

<template>
  <Select
    :model-value="props.column?.getFilterValue() as string | undefined"
    @update:model-value="(val) => props.column?.setFilterValue(val)"
  >
    <SelectTrigger class="w-45">
      <SelectValue :placeholder="title" />
    </SelectTrigger>
    <SelectContent>
      <SelectGroup>
        <SelectItem
          v-for="option in options"
          :key="option.value"
          :value="option.value"
        >
          {{ option.label }}
        </SelectItem>
      </SelectGroup>
    </SelectContent>
  </Select>
</template>
